### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Beginning support adding nix flakes to this. 

So far I just got it to the point of doing: 

```
nix develop
cp .env.example .env
just run-mint
```

The harder stuff will be around flutter that I do not have experience with.

### CODE REVIEW

**Comment by ngutech21** [comment]
I chose to remove the flutter-wallet as it was causing me more trouble than convenience. I am already working on a new web-wallet in pure Rust. Is there anything else you want to add to this PR?

**Comment by TonyGiorgio** [comment]
> web-wallet in pure Rust

Awesome to see! Do you know which framework you'll be going with? I'm curious. 

>  Is there anything else you want to add to this PR?

In that case, lemme try running some of the other commands and make sure there's full coverage. I can also get some postgresql stuff in here too.

**Comment by ngutech21** [comment]
> > web-wallet in pure Rust
> 
> Awesome to see! Do you know which framework you'll be going with? I'm curious.
> 
At the moment I am looking into leptos-rs. It's still early in development, but already has a growing community and ecosystem. I think it is a good fit for writing pure Rust pwas.

**Comment by ngutech21** [comment]
Thanks for your contribution

**Pull request merged**
